name: CI

on: [push]

#on: [workflow_dispatch]

#on: 
#  workflow_dispatch:
#  push:
#    tags:
#      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-docker:
    name: "Build"
    container: "wpilib/roborio-cross-ubuntu:2024-22.04"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Fetch all history and metadata
        run: |
          git config --global --add safe.directory /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}
      - name: Build vendordep 
        run: (cd vendor-template && ./gradlew publish --max-workers 1)
      - name: Build robot project
        run: ./gradlew build --max-workers 1